extends: airbnb-base
env:
  node: true
  browser: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true
rules:
  generator-star-spacing:
    - 2
    - before: true
      after: true
  no-shadow: 0
  no-restricted-syntax: 0
  no-return-assign: 0
  import/no-unresolved: 0
  import/extensions: 0
  require-yield: 0
  no-empty: 0
  no-param-reassign: 0
  comma-dangle: 0
  no-underscore-dangle: 0
  no-control-regex: 0
  class-methods-use-this: 0
  import/no-extraneous-dependencies:
    - 2
    - devDependencies: true
  func-names: 0
  no-unused-expressions: 0
  prefer-arrow-callback: 1
  no-use-before-define:
    - 2
    - functions: false
  space-before-function-paren:
    - 2
    - always
  max-len:
    - 2
    - 500
    - 2
  semi:
    - 2
    - never
  strict:
    - 2
    - global
  arrow-parens:
    - 2
    - always
  camelcase: 0
  no-unused-vars: 0
  import/prefer-default-export: 0
  prefer-promise-reject-errors: 0
  consistent-return: 0
  new-cap: 0
  no-restricted-globals: 0
  linebreak-style: ["error", "windows"]
